In [4]:
# numpy arrays

In [5]:
import numpy as np

In [6]:
mylist = list(range(1,51))

In [8]:
mylist_array = np.array(mylist)

In [9]:
mylist_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [10]:
type(mylist_array)

numpy.ndarray

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,28,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [33]:
len(np.linspace(0,10,9))

9

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [37]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
np.random.rand(3,2)

array([[0.71612169, 0.70194808],
       [0.37446747, 0.71088141],
       [0.51186631, 0.35960578]])

In [43]:
#nnumbers between 0 and 1
np.random.rand(5)

array([0.33337786, 0.94785871, 0.08971702, 0.233825  , 0.37063293])

In [53]:
np.random.randint(1,5,(4,5))

array([[4, 3, 3, 4, 2],
       [2, 1, 3, 3, 1],
       [2, 1, 1, 1, 1],
       [1, 4, 4, 1, 4]])

In [54]:
np.random.randint(1,101,5)

array([69,  3, 77, 18, 49])

In [58]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [59]:
arr = np.arange(1,26)

In [61]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [60]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [75]:
randArr = np.random.randint(5,51,9)


In [76]:
randArr

array([ 6, 28, 48, 34, 42,  6, 25, 37, 16])

In [77]:
randArr.max()

48

In [78]:
randArr.min()

6

In [79]:
randArr.argmin()

0

In [80]:
randArr.argmax()

2

In [81]:
randArr.dtype

dtype('int64')

In [82]:
randArr.shape

(9,)

In [83]:
randArr.reshape(3,3)

array([[ 6, 28, 48],
       [34, 42,  6],
       [25, 37, 16]])

In [86]:
randArr.reshape(1,9)

array([[ 6, 28, 48, 34, 42,  6, 25, 37, 16]])

In [87]:
arr1 = np.random.randint(1,85,12)

In [88]:
arr1


array([58, 22, 49, 59, 42, 60, 80, 15, 62, 62, 47, 62])

In [89]:
arr1[0]

58

In [91]:
arr1[1:5]

array([22, 49, 59, 42])

In [93]:
arr1[:5]

array([58, 22, 49, 59, 42])

In [94]:
arr1[5]

60

In [96]:
arr1[5:]

array([60, 80, 15, 62, 62, 47, 62])

In [97]:
arr1[0:5]= 200

In [98]:
arr1

array([200, 200, 200, 200, 200,  60,  80,  15,  62,  62,  47,  62])

In [101]:
arr1 = np.arange(0,11)

In [102]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
slice_of_arr1 = arr1[:5]

In [104]:
slice_of_arr1


array([0, 1, 2, 3, 4])

In [105]:
#colon means from beginning to end
#it behaves as a pointer
slice_of_arr1[:] = 99

In [106]:
arr1

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [122]:
#copy methode

arr1 = np.arange(0,11)

In [123]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
arr1_copy = arr1.copy()

In [125]:
arr1_copy


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [126]:
arr1_copy[:5] = -1

In [127]:
arr1_copy

array([-1, -1, -1, -1, -1,  5,  6,  7,  8,  9, 10])

In [128]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
#indexing on 2d arrays

In [134]:
arr_2d = np.arange(1,10)

In [137]:
arr_2d = arr_2d.reshape(3,3)

In [138]:
arr_2d.shape

(3, 3)

In [139]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [142]:
arr_2d[0]

array([1, 2, 3])

In [144]:
arr_2d[0][1]

2

In [145]:
arr_2d[1]

array([4, 5, 6])

In [146]:
arr_2d[1,2]


6

In [149]:
arr_2d[:1,1:]

array([[2, 3]])

In [150]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
arr_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [154]:
arr_2d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [155]:
arr_2d[1:,2]

array([6, 9])

In [158]:
arr3 = np.arange(0,11)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [159]:
arr3 > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True])

In [164]:
bool_arr3 = arr3 > 8

In [165]:
arr3[bool_arr3]

array([ 9, 10])

In [166]:
arr4 = np.arange(0,11)

In [169]:
# getting array based on comparison
arr4[arr4>8]

array([ 9, 10])

In [170]:
arr5 = np.arange(11)

In [171]:
arr5


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [173]:
arr5 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [174]:
arr5 -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [175]:
arr5 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [176]:
arr5 * arr5

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [177]:
arr5 / arr5

/tmp/ipykernel_6069/4215261564.py:1: RuntimeWarning: invalid value encountered in divide
  arr5 / arr5


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [178]:
1 / arr5

/tmp/ipykernel_6069/1138687670.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr5


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [179]:
np.sqrt(arr5)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [180]:
np.log(arr5)

/tmp/ipykernel_6069/667223671.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr5)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [181]:
np.sin(arr5)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [182]:
arr5.sum()

55

In [183]:
arr5.min()

0

In [184]:
arr5.max()

10

In [185]:
arr5.std()

3.1622776601683795

In [186]:
arr5.var()

10.0

In [187]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [188]:
arr5_2d = np.arange(0,25).reshape(5,5)

In [190]:
arr5_2d


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [191]:
arr5_2d.sum()

300

In [194]:
#sum accross rows
arr5_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [196]:
#sum accross columns
arr5_2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])